### ISSUE TITLE
Buggy on plasma 6.1 (black background)

### ISSUE THREAD

**Issue by dgudim** [Schneegans/Burn-My-Windows#443]
## Describe the Bug
Upon effect activation the window turns black and that black rectangle is animated

1. Install effect from kde store
2. Use it

## System
_Please complete the following information:_
 - Linux distribution: Arch
 - Burn-My-Windows version: Latest from kde store
 - Plasma 6.1.0, Qt 6.7.1, frameworks 6.3.0

[Screencast_20240620_133957.webm](https://github.com/Schneegans/Burn-My-Windows/assets/34401005/ed874b79-0eff-4184-92da-efb08d6ffcaf)

**Comment by Schneegans** [comment]
Hi there! Thanks for the report. Does this happen with all applications? Or just with specific ones? And did you observe this with older Plasma versions as well?

I would assume that this is an issue in KWin and not something we can fix on the effect side of things...

**Comment by dgudim** [comment]
Sorry for the delay. Yeah, after some tinkering I think this is a kwin bug, this happens after wake from sleep/hibernate in about 10% of the cases (on amd and nvidia, but not on intel it seems). I am not able to consistently reproduce this though :(

**Comment by nask0** [comment]
> Sorry for the delay. Yeah, after some tinkering I think this is a kwin bug, this happens after wake from sleep/hibernate in about 10% of the cases (on amd and nvidia, but not on intel it seems). I am not able to consistently reproduce this though :(

I had a similar issue while ago, was persistent on my old machine at some point. Creating a new user fixed the issue than, IIRC it was some messy configuration on `~/.config/` somewhere but was unable to narrow down further.

**Comment by KR3C1K** [comment]
My case is similar.
Wayland has a issue with this, on X11 works fine.
But when on wayland in the terminal I type:
`dbus-run-session startplasma-wayland`
The window with the wayland session opens, and here all effects work correctly.

**Comment by yuyuyak** [comment]
[Effect-kwin4_effect_fire]
3DNoise=true
Gradient1=invalid
Gradient1=invalid
Gradient1=invalid

**Comment by yuyuyak** [comment]
Also, when starting kwin manually, it complains that $HOME/.local/share/kwin/effects/kwin4_effect_fire/metadata.json has a string setting for EnabledByDefault, when it should be boolean, so I changed this line in the file:
`EnabledByDefault": "false",`
`to`
`EnabledByDefault": 0,`
Maybe my imagination, but seems to work smoother now.

**Comment by nask0** [comment]
> Also, when starting kwin manually, it complains that $HOME/.local/share/kwin/effects/kwin4_effect_fire/metadata.json has a string setting for EnabledByDefault, when it should be boolean, so I changed this line in the file: `EnabledByDefault": "false",` `to` `EnabledByDefault": 0,` Maybe my imagination, but seems to work smoother now.

I believe this is fixed in the latest relase ([here](https://github.com/Schneegans/Burn-My-Windows/blob/main/kwin/metadata.json.in#L16))

**Comment by KR3C1K** [comment]
Unfortunately, I did not find an answer to my problem. 
> I think perhaps you adjusted the config and the config gets written improperly in kwinrc. I installed it on plasma 6.1 also, here's an example mod on the config it wrote for me:
> 
> `[Effect-kwin4_effect_fire]` `3DNoise=true` `Gradient1=invalid` `Gradient2=invalid` `Gradient3=invalid` `Gradient4=invalid` `Gradient5=invalid`
> 
> It doesn't like the Gradient[1-5]=invalid entries and I get exactly the same results described above. If you simply remove those it works properly again after logging out and back in, no need for complete reboot. A bit of a nuisance if you want to play with the config and I have no idea what to do with the gradient settings (color picker?), but it's no problem after that's done.

In my effect configuration with standard settings these variables are missing, they appear when I set the colors myself, but it still does not change anything in the operation of the effect, and I would say that it is worse.
Out of curiosity I checked the other effects from burn my windows and each of the effects has the same problem.....
And I still don't know why they don't work properly in Wayland at my place, but when I fire up in X11 every effect works properly.

**Comment by Kagarrache** [comment]
Do you have a color profile selected in "Display & Monitor"? 

According to [this report](https://bugs.kde.org/show_bug.cgi?id=477017) it can cause these kind of problems... and setting it to "None" worked for me

**Comment by KR3C1K** [comment]
> Do you have a color profile selected in "Display & Monitor"?
> 
> According to [this report](https://bugs.kde.org/show_bug.cgi?id=477017) it can cause these kind of problems... and setting it to "None" worked for me

I really don't believe it. I struggled with this for so long. My colleague thanks for this information. I never would have come across that the problem is related to color profiles, I had it set to built-in. I set it to “NONE” and everything works as it should. I am really grateful to you.

**Comment by Schneegans** [comment]
So I think this is a duplicate of #432, right? If so, it could be fixed in the latest `main` branch. Does anybody want to test this?
